In [29]:
import numpy as np
W = np.array([-1,1]).reshape(1,2)
b = 1
p1 = np.array([-1,1]).reshape(2,1)
p2 = np.array([-1,-1]).reshape(2,1)
p3 = np.array([0,0]).reshape(2,1)
p4 = np.array([1,0]).reshape(2,1)
t1 = 1
t2 = 1
t3 = 0
t4 = 0

In [30]:
def hardlim(x):
    if x>=0:
        return 1
    else:
        return 0

In [31]:
print(hardlim(np.dot(W,p2)+b))

1


In [32]:
e = t2 - hardlim(np.dot(W,p2)+b)
W = W + e*p2.T
b = b + e
print(W, b, e)

[[-1  1]] 1 0


In [33]:
print(hardlim(np.dot(W,p3)+b))

1


In [34]:
e = t3 - hardlim(np.dot(W,p3)+b)
W = W + e*p3.T
b = b + e
print(W, b, e)

[[-1  1]] 0 -1


In [35]:
e = t4 - hardlim(np.dot(W,p4)+b)
W = W + e*p4.T
b = b + e   
print(W, b, e)

[[-1  1]] 0 0


In [37]:
print(hardlim(np.dot(W,p1)+b), t1)

1 1


In [38]:
e = t1 - hardlim(np.dot(W,p1)+b)
W = W + e*p1.T
b = b + e
print(e, W, b)

0 [[-1  1]] 0


In [39]:
print(hardlim(np.dot(W,p2)+b), t2)

1 1


In [40]:
e = t2 - hardlim(np.dot(W,p2)+b)
W = W + e*p2.T
b = b + e
print(e, W, b)

0 [[-1  1]] 0


In [41]:
print(hardlim(np.dot(W,p3)+b), t3)

1 0


In [42]:
e = t3 - hardlim(np.dot(W,p3)+b)
W = W + e*p3.T
b = b + e
print(e, W, b)

-1 [[-1  1]] -1


In [43]:
print(hardlim(np.dot(W,p4)+b), t4)

0 0


In [44]:
print(hardlim(np.dot(W,p1)+b), t1)

1 1


In [45]:
print(hardlim(np.dot(W,p2)+b), t2)

0 1


In [46]:
e = t2 - hardlim(np.dot(W,p2)+b)
W = W + e*p2.T
b = b + e
print(e, W, b)

1 [[-2  0]] 0


In [47]:
print(hardlim(np.dot(W,p3)+b), t3)

1 0


In [48]:
e = t3 - hardlim(np.dot(W,p3)+b)
W = W + e*p3.T
b = b + e
print(e, W, b)

-1 [[-2  0]] -1


In [49]:
print(hardlim(np.dot(W,p4)+b), t4)

0 0


In [50]:
print(hardlim(np.dot(W,p1)+b), t1)

1 1


In [51]:
print(hardlim(np.dot(W,p2)+b), t2)

1 1


In [52]:
print(hardlim(np.dot(W,p3)+b), t3)

0 0


In [53]:
print(hardlim(np.dot(W,p4)+b), t4)

0 0


In [ ]:
import numpy as np
W = np.array([0,0],[0,0]).reshape(2,2)
b = 0
p1 = np.array([-1,1]).reshape(2,1)
p2 = np.array([-1,-1]).reshape(2,1)
p3 = np.array([0,0]).reshape(2,1)
p4 = np.array([1,0]).reshape(2,1)
t1 = 1
t2 = 1
t3 = 0
t4 = 0