In [68]:
import numpy as np
W = np.array([-1,1]).reshape(1,2)
b = 1
p1 = np.array([-1,1]).reshape(2,1)
p2 = np.array([-1,-1]).reshape(2,1)
p3 = np.array([0,0]).reshape(2,1)
p4 = np.array([1,0]).reshape(2,1)
t1 = 1
t2 = 1
t3 = 0
t4 = 0

In [69]:
def hardlim(x):
    if x>=0:
        return 1
    else:
        return 0

In [70]:
def hardlim_vector(nums):
    return np.array([hardlim(x) for x in nums]).reshape(nums.shape)

In [71]:
print(hardlim(np.dot(W,p2)+b))

1


In [72]:
e = t2 - hardlim(np.dot(W,p2)+b)
W = W + e*p2.T
b = b + e
print(W, b, e)

[[-1  1]] 1 0


In [73]:
print(hardlim(np.dot(W,p3)+b))

1


In [74]:
e = t3 - hardlim(np.dot(W,p3)+b)
W = W + e*p3.T
b = b + e
print(W, b, e)

[[-1  1]] 0 -1


In [75]:
e = t4 - hardlim(np.dot(W,p4)+b)
W = W + e*p4.T
b = b + e   
print(W, b, e)

[[-1  1]] 0 0


In [76]:
print(hardlim(np.dot(W,p1)+b), t1)

1 1


In [77]:
e = t1 - hardlim(np.dot(W,p1)+b)
W = W + e*p1.T
b = b + e
print(e, W, b)

0 [[-1  1]] 0


In [78]:
print(hardlim(np.dot(W,p2)+b), t2)

1 1


In [79]:
e = t2 - hardlim(np.dot(W,p2)+b)
W = W + e*p2.T
b = b + e
print(e, W, b)

0 [[-1  1]] 0


In [80]:
print(hardlim(np.dot(W,p3)+b), t3)

1 0


In [81]:
e = t3 - hardlim(np.dot(W,p3)+b)
W = W + e*p3.T
b = b + e
print(e, W, b)

-1 [[-1  1]] -1


In [82]:
print(hardlim(np.dot(W,p4)+b), t4)

0 0


In [83]:
print(hardlim(np.dot(W,p1)+b), t1)

1 1


In [84]:
print(hardlim(np.dot(W,p2)+b), t2)

0 1


In [85]:
e = t2 - hardlim(np.dot(W,p2)+b)
W = W + e*p2.T
b = b + e
print(e, W, b)

1 [[-2  0]] 0


In [86]:
print(hardlim(np.dot(W,p3)+b), t3)

1 0


In [87]:
e = t3 - hardlim(np.dot(W,p3)+b)
W = W + e*p3.T
b = b + e
print(e, W, b)

-1 [[-2  0]] -1


In [88]:
print(hardlim(np.dot(W,p4)+b), t4)

0 0


In [89]:
print(hardlim(np.dot(W,p1)+b), t1)

1 1


In [90]:
print(hardlim(np.dot(W,p2)+b), t2)

1 1


In [91]:
print(hardlim(np.dot(W,p3)+b), t3)

0 0


In [92]:
print(hardlim(np.dot(W,p4)+b), t4)

0 0


In [93]:
import numpy as np
W = np.array([[0.5,0.5],[0.5,0.5]]).reshape(2,2)
b = 0
p1_1 = np.array([-1,1]).reshape(2,1)
p1_2 = np.array([-1,0]).reshape(2,1)
p2_1 = np.array([0,2]).reshape(2,1)
p2_2 = np.array([1,2]).reshape(2,1)
p3_1 = np.array([2,0]).reshape(2,1)
p3_2 = np.array([2,1]).reshape(2,1)
p4_1 = np.array([1,-1]).reshape(2,1)
p4_2 = np.array([0,-1]).reshape(2,1)
t1 = np.array([1,0]).reshape(2,1)
t2 = np.array([0,0]).reshape(2,1)
t3 = np.array([0,1]).reshape(2,1)
t4 = np.array([1,1]).reshape(2,1)

In [94]:
a = hardlim_vector(np.dot(W,p1_1)+b)
e = t1 - a

In [95]:
W = W + np.dot(e,p1_1.T)
b = b + e
print(W, b)

[[ 0.5  0.5]
 [ 1.5 -0.5]] [[ 0]
 [-1]]


In [96]:
a = hardlim_vector(np.dot(W,p1_2)+b)
print(a)
e = t1 - a
print(e)
W = W + np.dot(e,p1_2.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[1]
 [0]]
[[-0.5  0.5]
 [ 1.5 -0.5]]
[[ 1]
 [-1]]


In [97]:
a = hardlim_vector(np.dot(W,p2_1)+b)
print(a)
e = t2 - a
print(e)
W = W + np.dot(e,p2_1.T)
b = b + e
print(W)
print(b)

[[1]
 [0]]
[[-1]
 [ 0]]
[[-0.5 -1.5]
 [ 1.5 -0.5]]
[[ 0]
 [-1]]


In [98]:
a = hardlim_vector(np.dot(W,p2_2)+b)
print(a)
e = t2 - a
print(e)
W = W + np.dot(e,p2_2.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[0]
 [0]]
[[-0.5 -1.5]
 [ 1.5 -0.5]]
[[ 0]
 [-1]]


In [99]:
a = hardlim_vector(np.dot(W,p3_1)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_1.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-0.5 -1.5]
 [ 1.5 -0.5]]
[[ 0]
 [-1]]


In [100]:
a = hardlim_vector(np.dot(W,p3_2)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_2.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-0.5 -1.5]
 [ 1.5 -0.5]]
[[ 0]
 [-1]]


In [101]:
a = hardlim_vector(np.dot(W,p4_2)+b)
print(a)
e = t4 - a
print(e)
W = W + np.dot(e,p4_2.T)
b = b + e
print(W)
print(b)

[[1]
 [0]]
[[0]
 [1]]
[[-0.5 -1.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [102]:
a = hardlim_vector(np.dot(W,p1_1)+b)
print(a)
e = t1 - a
print(e)
W = W + np.dot(e,p1_1.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[1]
 [0]]
[[-1.5 -0.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [103]:
a = hardlim_vector(np.dot(W,p1_2)+b)
print(a)
e = t1 - a
print(e)
W = W + np.dot(e,p1_2.T)
b = b + e
print(W)
print(b)

[[1]
 [0]]
[[0]
 [0]]
[[-1.5 -0.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [104]:
a = hardlim_vector(np.dot(W,p2_1)+b)
print(a)
e = t2 - a
print(e)
W = W + np.dot(e,p2_1.T)
b = b + e
print(W)
print(b)

[[1]
 [0]]
[[-1]
 [ 0]]
[[-1.5 -2.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [105]:
a = hardlim_vector(np.dot(W,p2_2)+b)
print(a)
e = t2 - a
print(e)
W = W + np.dot(e,p2_2.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[0]
 [0]]
[[-1.5 -2.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [106]:
a = hardlim_vector(np.dot(W,p3_1)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_1.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-1.5 -2.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [107]:
a = hardlim_vector(np.dot(W,p3_2)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_2.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-1.5 -2.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [108]:
a = hardlim_vector(np.dot(W,p4_1)+b)
print(a)
e = t4 - a
print(e)
W = W + np.dot(e,p4_1.T)
b = b + e
print(W)
print(b)

[[1]
 [1]]
[[0]
 [0]]
[[-1.5 -2.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [109]:
a = hardlim_vector(np.dot(W,p4_2)+b)
print(a)
e = t4 - a
print(e)
W = W + np.dot(e,p4_2.T)
b = b + e
print(W)
print(b)

[[1]
 [1]]
[[0]
 [0]]
[[-1.5 -2.5]
 [ 1.5 -1.5]]
[[0]
 [0]]


In [110]:
a = hardlim_vector(np.dot(W,p1_1)+b)
print(a)
e = t1 - a
print(e)
W = W + np.dot(e,p1_1.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[1]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [111]:
a = hardlim_vector(np.dot(W,p1_2)+b)
print(a)
e = t1 - a
print(e)
W = W + np.dot(e,p1_2.T)
b = b + e
print(W)
print(b)

[[1]
 [0]]
[[0]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [112]:
a = hardlim_vector(np.dot(W,p2_1)+b)
print(a)
e = t2 - a
print(e)
W = W + np.dot(e,p2_1.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[0]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [113]:
a = hardlim_vector(np.dot(W,p2_2)+b)
print(a)
e = t2 - a
print(e)
W = W + np.dot(e,p2_2.T)
b = b + e
print(W)
print(b)

[[0]
 [0]]
[[0]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [114]:
a = hardlim_vector(np.dot(W,p3_1)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_1.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [115]:
a = hardlim_vector(np.dot(W,p3_2)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_2.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [116]:
a = hardlim_vector(np.dot(W,p3_2)+b)
print(a)
e = t3 - a
print(e)
W = W + np.dot(e,p3_2.T)
b = b + e
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-2.5 -1.5]
 [ 1.5 -1.5]]
[[1]
 [0]]


In [117]:
W = np.array([[-1,-1],[1,-1]]).reshape(2,2)
b = np.array([1,0]).reshape(2,1)
p1_1 = np.array([-1,1]).reshape(2,1)
p1_2 = np.array([-1,0]).reshape(2,1)
p2_1 = np.array([0,2]).reshape(2,1)
p2_2 = np.array([1,2]).reshape(2,1)
p3_1 = np.array([2,0]).reshape(2,1)
p3_2 = np.array([2,1]).reshape(2,1)
p4_1 = np.array([1,-1]).reshape(2,1)
p4_2 = np.array([0,-1]).reshape(2,1)
t1 = np.array([1,0]).reshape(2,1)
t2 = np.array([0,0]).reshape(2,1)
t3 = np.array([0,1]).reshape(2,1)
t4 = np.array([1,1]).reshape(2,1)

In [118]:
a11 = hardlim_vector(np.dot(W,p1_1)+b)
e11 = t1 - a11
print(a11)
print(e11)

[[1]
 [0]]
[[0]
 [0]]


In [119]:
a12 = hardlim_vector(np.dot(W,p1_2)+b)
e12 = t1 - a12
print(a12)
print(e12)

[[1]
 [0]]
[[0]
 [0]]


In [120]:
a21 = hardlim_vector(np.dot(W,p2_1)+b)  
e21 = t2 - a21
print(a21)
print(e21)


[[0]
 [0]]
[[0]
 [0]]


In [121]:
a22 = hardlim_vector(np.dot(W,p2_2)+b)
e22 = t2 - a22
print(a22)
print(e22)

[[0]
 [0]]
[[0]
 [0]]


In [122]:
a31 = hardlim_vector(np.dot(W,p3_1)+b)
e31 = t3 - a31
print(a31)
print(e31)

[[0]
 [1]]
[[0]
 [0]]


In [123]:
a32 = hardlim_vector(np.dot(W,p3_2)+b)
e32 = t3 - a32
print(a32)
print(e32)

[[0]
 [1]]
[[0]
 [0]]


In [124]:
a41 = hardlim_vector(np.dot(W,p4_1)+b)
e41 = t4 - a41
print(a41)
print(e41)

[[1]
 [1]]
[[0]
 [0]]


In [125]:
a42 = hardlim_vector(np.dot(W,p4_2)+b)
e42 = t4 - a42
print(a42)
print(e42)

[[1]
 [1]]
[[0]
 [0]]


In [126]:
p1_3= np.array([-1,-3]).reshape(2,1)
a13 = hardlim_vector(np.dot(W,p1_3)+b)
e13 = t1 - a13
print(a13)
print(e13)
W = W + np.dot(e13,p1_3.T)
b = b + e13
print(W)
print(b)

[[1]
 [1]]
[[ 0]
 [-1]]
[[-1 -1]
 [ 2  2]]
[[ 1]
 [-1]]


In [127]:
a11 = hardlim_vector(np.dot(W,p1_1)+b)
e11 = t1 - a11
print(a11)
print(e11)


[[1]
 [0]]
[[0]
 [0]]


In [128]:
a12 = hardlim_vector(np.dot(W,p1_2)+b)
e12 = t1 - a12
print(a12)
print(e12)

[[1]
 [0]]
[[0]
 [0]]


In [129]:
a21 = hardlim_vector(np.dot(W,p2_1)+b)
e21 = t2 - a21
print(a21)
print(e21)
W = W + np.dot(e21,p2_1.T)
b = b + e21
print(W)
print(b)

[[0]
 [1]]
[[ 0]
 [-1]]
[[-1 -1]
 [ 2  0]]
[[ 1]
 [-2]]


In [130]:
a22 = hardlim_vector(np.dot(W,p2_2)+b)
e22 = t2 - a22
print(a22)
print(e22)
W = W + np.dot(e22,p2_2.T)
b = b + e22
print(W)
print(b)

[[0]
 [1]]
[[ 0]
 [-1]]
[[-1 -1]
 [ 1 -2]]
[[ 1]
 [-3]]


In [131]:
a31 = hardlim_vector(np.dot(W,p3_1)+b)
e31 = t3 - a31
print(a31)
print(e31)
W = W + np.dot(e31,p3_1.T)
b = b + e31
print(W)
print(b)

[[0]
 [0]]
[[0]
 [1]]
[[-1 -1]
 [ 3 -2]]
[[ 1]
 [-2]]


In [132]:
a32 = hardlim_vector(np.dot(W,p3_2)+b)
e32 = t3 - a32
print(a32)
print(e32)
W = W + np.dot(e32,p3_2.T)
b = b + e32
print(W)
print(b)

[[0]
 [1]]
[[0]
 [0]]
[[-1 -1]
 [ 3 -2]]
[[ 1]
 [-2]]


In [133]:
a41 = hardlim_vector(np.dot(W,p4_1)+b)  
e41 = t4 - a41
print(a41)
print(e41)
W = W + np.dot(e41,p4_1.T)
b = b + e41
print(W)
print(b)


[[1]
 [1]]
[[0]
 [0]]
[[-1 -1]
 [ 3 -2]]
[[ 1]
 [-2]]


In [134]:
a42 = hardlim_vector(np.dot(W,p4_2)+b)
e42 = t4 - a42
print(a42)
print(e42)
W = W + np.dot(e42,p4_2.T)
b = b + e42
print(W)
print(b)


[[1]
 [1]]
[[0]
 [0]]
[[-1 -1]
 [ 3 -2]]
[[ 1]
 [-2]]
